# Travis-CI configuration for Bioconductor packages
# https://docs.travis-ci.com/user/languages/r

# How Travis builds R packages:
# https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/r.rb

# Can we use build stages to cache the Bioconductor package library?
# https://docs.travis-ci.com/user/build-stages
# https://docs.travis-ci.com/user/build-stages/warm-cache/

# Temporarily enable `script: true` when caching package library.
# https://gist.github.com/mjsteinbaugh/47d9a7aecdd8c3c1962a3247d791635f

# script: true
# r_build_args: "--no-build-vignettes"
# r_check_args: "--no-vignettes"

language: r
cache: packages
sudo: false
bioc_required: true

matrix:
  include:
  - os: osx
    r: bioc-release
    script: false
    fortran: false
    latex: false
    warnings_are_errors: true
  - os: linux
    r: bioc-release
    script: false
    warnings_are_errors: true
  # - os: linux
  #   r: bioc-devel
  #   script: false
  #   latex: false
  #   warnings_are_errors: true
  fast_finish: true

env:
  global:
    - LINTR_COMMENT_BOT=true

r_packages:
  - covr
bioc_packages:
  - BiocCheck
  - EnsDb.Hsapiens.v75
github_packages:
  - jimhester/lintr

after_success:
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'covr::codecov()'
  - R CMD BiocCheck .

notifications:
  email:
    recipients:
      - mike@steinbaugh.com
    on_success: change
    on_failure: always
