# Travis-CI configuration for Bioconductor packages
#
# See also:
# - https://docs.travis-ci.com/user/languages/r
# - https://docs.travis-ci.com/user/environment-variables/
# - https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/r.rb
# - https://jef.works/blog/2019/02/17/automate-testing-of-your-R-package/

language: r
cache: packages

matrix:
  include:
    - os: linux
      r: bioc-release
    - os: linux
      r: bioc-devel
    - os: osx
      r: bioc-release
  allow_failures:
    - os: osx
    - r: bioc-devel
  fast_finish: true

branches:
  only:
    - master

env:
  global:
    - LINTR_COMMENT_BOT=true

r_packages:
  - covr
bioc_packages:
  - BiocCheck
r_github_packages:
  - acidgenomics/lintr

after_success:
  - R CMD BiocCheck .
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    recipients:
      - mike@steinbaugh.com
    on_success: change
    on_failure: change

# Temporarily enable when caching package library.
# script: true

# Avoid timeouts on long steps (e.g. codecov report).
# https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
# install: travis_wait mvn install
# install: travis_wait 30 mvn install

# Skip building vignettes, which can cause the Travis build to time out.
# r_build_args: "--no-build-vignettes --no-manual"
# r_check_args: "--no-build-vignettes --no-manual --timings"
