# Travis-CI configuration for Bioconductor packages
#
# See also:
# - https://docs.travis-ci.com/user/languages/r
# - https://docs.travis-ci.com/user/environment-variables/
# - https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/r.rb
# - https://jef.works/blog/2019/02/17/automate-testing-of-your-R-package/

# Temporarily enable when caching package library.
# script: true

language: r
cache: packages

matrix:
  include:
    - os: linux
      r: bioc-release
    - os: linux
      r: bioc-devel
    - os: osx
      r: bioc-release
  allow_failures:
    - os: osx
    - r: bioc-devel
  fast_finish: true

# Safelist (only these branches)
branches:
  only:
    - master

# Blocklist (everything but these branches)
# branches:
#   except:
#     - develop

env:
  global:
    - LINTR_COMMENT_BOT=true

# Skipping vignettes, which can cause the build to time out.
r_build_args: "--no-build-vignettes --no-manual"
r_check_args: "--no-build-vignettes --no-manual --timings"

r_packages:
  - covr
bioc_packages:
  - BiocCheck
  - EnsDb.Hsapiens.v75
github_packages:
  - acidgenomics/lintr

after_success:
  - R CMD BiocCheck .
  # Only check lints and coverage against linux bioc-release.
  - test $TRAVIS_OS_NAME = 'linux' && $TRAVIS_R_VERSION_STRING = 'bioc-release' && Rscript -e 'lintr::lint_package()'
  - test $TRAVIS_OS_NAME = 'linux' && $TRAVIS_R_VERSION_STRING = 'bioc-release' && Rscript -e 'covr::codecov()'

notifications:
  email:
    recipients:
      - mike@steinbaugh.com
    on_success: change
    on_failure: change
