# R for travis
# https://docs.travis-ci.com/user/languages/r
language: r
sudo: false
cache: packages
dist: trusty
r:
  - bioc-release
  - bioc-devel
r_github_packages:
  - r-lib/covr
after_success:
  - Rscript -e 'covr::codecov()'
