# Travis-CI configuration for Bioconductor packages
# https://docs.travis-ci.com/user/languages/r

# How Travis builds R packages:
# https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/r.rb

# Can we use build stages to warm the Bioconductor library cache?
# https://docs.travis-ci.com/user/build-stages
# https://docs.travis-ci.com/user/build-stages/warm-cache/

# Temporarily enable when caching package library.
# script: true

# r_build_args: "--no-build-vignettes"
# r_check_args: "--no-vignettes"

language: r
cache: packages
sudo: false
bioc_required: true

matrix:
  include:
  - os: linux
    r: bioc-release
    warnings_are_errors: true
  - os: osx
    r: bioc-release
    fortran: false
    latex: false
    warnings_are_errors: true

env:
  global:
    - LINTR_COMMENT_BOT=true

r_packages:
  - covr
bioc_packages:
  - BiocCheck
  - EnsDb.Hsapiens.v75
github_packages:
  - mjsteinbaugh/lintr

after_success:
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'covr::codecov()'
  - R CMD BiocCheck .

notifications:
  email:
    recipients:
      - mike@steinbaugh.com
    on_success: change
    on_failure: always
