# Travis-CI configuration for Bioconductor packages
#
# See also:
# - https://docs.travis-ci.com/user/languages/r
# - https://docs.travis-ci.com/user/environment-variables/
# - https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/r.rb
# - https://jef.works/blog/2019/02/17/automate-testing-of-your-R-package/

script: true

language: r
cache: packages
bioc_required: true
bioc_check: true
use_devtools: true

matrix:
  include:
    - os: linux
      r: bioc-release
    - os: linux
      r: bioc-devel
    - os: osx
      r: bioc-release
  allow_failures:
    - os: osx
    - r: bioc-devel
  fast_finish: true

branches:
  only:
    - master

env:
  global:
    - LINTR_COMMENT_BOT=true

r_packages:
  - covr
r_github_packages:
  - acidgenomics/lintr

after_success:
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    recipients:
      - mike@steinbaugh.com
    on_success: change
    on_failure: change
