# R for travis
# https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
warnings_are_errors: true

# Temporarily enable to cache R packages
script: true

notifications:
  email:
    on_success: change
    on_failure: change

r:
  - bioc-release
  - bioc-devel

r_packages:
  - covr
bioc_packages:
  - BiocCheck

after_success:
  - Rscript -e 'covr::codecov()'
  - R CMD BiocCheck .
