# Travis-CI configuration for Bioconductor packages
# https://docs.travis-ci.com/user/languages/r

# How Travis builds R packages:
# https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/r.rb

# Temporarily enable when caching package library.
# script: true

# r_build_args: "--no-build-vignettes"
# r_check_args: "--no-vignettes"

language: r
cache: packages

matrix:
  include:
  - os: linux
    r: bioc-release
  - os: osx
    r: bioc-release

# blocklist
# branches:
#   except:
#   - develop

# safelist
branches:
  only:
  - master

env:
  global:
    - LINTR_COMMENT_BOT=true

r_packages:
  - covr
bioc_packages:
  - BiocCheck
  - EnsDb.Hsapiens.v75
github_packages:
  - mjsteinbaugh/lintr

after_success:
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'covr::codecov()'
  - R CMD BiocCheck .

notifications:
  email:
    recipients:
      - mike@steinbaugh.com
    on_success: change
    on_failure: change
