# AppVeyor-CI configuration for Bioconductor packages
# https://github.com/krlmlr/r-appveyor

init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

platform: x64

# cache:
#   - C:\RLibrary

branches:
  only:
    - master

environment:
  global:
    # r-appveyor will fail to install some packages (e.g. XML) unless we
    # specifically request binary packages.
    # https://github.com/krlmlr/r-appveyor/issues/133
    # https://github.com/krlmlr/r-appveyor/issues/138
    # Note that enabling this can cause R-devel builds to fail.
    # PKGTYPE: win.binary
    # Note that the more powerful `x64` image is now default over `i386`.
    R_ARCH: x64
    # Need to enable when installing GitHub dependency packages.
    USE_RTOOLS: true
  # Set the build matrix to use R-devel, otherwise Bioconductor checks will fail
  # because the image now expects BioC 3.9 on R 3.6.
  # https://github.com/krlmlr/r-appveyor/issues/144
  matrix:
    - R_VERSION: devel
      GCC_PATH: mingw_64

build_script:
  # `install_bioc_deps` will fail due to AnnotationHub unless we run these commands.
  - travis-tool.sh install_bioc GenomeInfoDbData
  - travis-tool.sh install_bioc DelayedArray
  - travis-tool.sh install_bioc ensembldb
  - travis-tool.sh install_bioc EnsDb.Hsapiens.v75
  # Now the Bioconductor dependencies will install.
  - travis-tool.sh install_bioc_deps
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits

notifications:
  - provider: Email
    to:
      - mike@steinbaugh.com
    on_build_status_changed: true
