# AppVeyor-CI configuration for Bioconductor packages
#
# See also:
# - https://github.com/krlmlr/r-appveyor
# - https://github.com/Bioconductor/BiocManager/blob/master/appveyor.yml
# - https://github.com/satijalab/seurat/blob/release/3.0/appveyor.yml

init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

platform: x64

branches:
  only:
    - master

environment:
  global:
    GCC_PATH: mingw_64
    # PKGTYPE: win.binary
    R_ARCH: x64
    USE_RTOOLS: true
  matrix:
    - R_VERSION: patched
      BIOC_USE_DEVEL: "FALSE"
    - R_VERSION: devel
      BIOC_USE_DEVEL: "TRUE"

matrix:
  allow_failures:
    - R_VERSION: devel

build_script:
  - travis-tool.sh install_bioc GenomeInfoDbData
  - travis-tool.sh install_bioc DelayedArray
  - travis-tool.sh install_bioc ensembldb
  - travis-tool.sh install_bioc_deps

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs
  - path: '*.Rcheck\**\*.out'
    name: Logs
  - path: '*.Rcheck\**\*.fail'
    name: Logs
  - path: '*.Rcheck\**\*.Rout'
    name: Logs
  - path: '\*_*.tar.gz'
    name: Bits
  - path: '\*_*.zip'
    name: Bits
  - path: all-Rout.zip
    name: AllRout

notifications:
  - provider: Email
    to:
      - mike@steinbaugh.com
    on_build_status_changed: true

cache:
  - C:\RLibrary -> appveyor.yml
